# Generated by Django 2.2 on 2021-05-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemates_appOne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Nickname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
